
version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "fraud-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/clients/0:/app/data

